import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const articleStructuredData = `{
    "@context": "https://schema.org/",
    "@type": "Article",
    "headline": "headline",
    "name": "name",
    "description": "description",
    "datePublished": "2023-04-25T08:16:25.298Z",
    "articleSection": "",
    "url": "url",
    "image": "https://orion-uploads.openroadmedia.com",
    "author": {
      "@type": "Person",
      "name": "Open Road Media"
    },
    "publisher": {
      "@type": "Organization",
      "name": "Open Road Media",
      "logo": {
        "@type": "ImageObject",
        "url": "url"
      }
    },
    "mainEntityOfPage": {
      "@type": "WebPage",
      "name": "Open Road Media",
      "@id": "id"
    }
  }`;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>
      Heallo
     </div>
     <script type="application/ld+json" dangerouslySetInnerHTML={{__html: articleStructuredData}} />
    </>
  )
}
